[tool.poetry]
name = "norfair"
version = "0.1.8"
description = "Lightweight Python library for real-time 2D object tracking."
license = "BSD-3-Clause"
authors = ["Tryolabs <hello@tryolabs.com>"]
repository = "https://github.com/tryolabs/norfair"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
filterpy = "^1.4.5"
rich = "^6.1.1"
opencv-python = ">= 3.2.0, < 5.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
# Had to disable black because of this: https://github.com/python-poetry/poetry/issues/2386
# Please install separately for development.
# black = "^20.8b1"
isort = "^5.5.1"
pylint = "^2.6.0"
tox = "^3.20.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
