[tool.poetry]
name = "norfair"
version = "2.0.0"
description = "Lightweight Python library for adding real-time multi-object tracking to any detector."
license = "BSD-3-Clause"
authors = ["Tryolabs <hello@tryolabs.com>"]
repository = "https://github.com/tryolabs/norfair"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
filterpy = "^1.4.5"
rich = ">=9.10.0, <13.0.0"
opencv-python = {version = ">= 3.2.0, < 5.0.0", optional = true}
motmetrics = {version = "1.2.0", optional = true}

[tool.poetry.extras]
metrics = ["motmetrics"]
video = ["opencv-python"]

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
pylint = "^2.6.0"
pytest = "^6.2.2"
tox = "^3.21.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
